[workspace]
resolver = "2"

members = [
    "block_sequence_spiral",
    "cross_validation",
    "data_multiple_timelines",
    "experiment_prediction",
    "full_fields_connector",
    "memory_cpu_full",
    "power_law_distance",
    "processor_cpu_full",
    "refract_recounter_cpu",
    "rnn_architecture",
    "row_col_coordinates_resolver",
    "signal_transferer_full_cpu",
    "simple_experiment_result",
    "simple_high_level_controller",
    "simple_result_reader",
    "simple_tick_controller",
    "stream_splitter_data_provider",
    "statshouse_data_iterator",
    "sync_binary_controller",
    "topology_restore_first"
]
