FROM rust:1.82 AS chef
RUN cargo install cargo-chef

RUN apt-get update && apt-get install -y ocl-icd-opencl-dev intel-opencl-icd ocl-icd-libopencl1

WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

COPY . .
