[layer_params]
field_width = 3
field_height = 4
layer_width = 5
layer_height = 1

[synapse_params]
alpha = 1.5
gamma_dec = 0.5
gamma_inc = 0.5
g_dec = 5.0
g_inc = 10
g_0 = 1.0
min_g = -10.0
max_g = 10.0
h = 0.5
refract_interval = 1
threshold_train = 0.9
threshold_predict_min = 0.2
threshold_predict_max = 0.4
signal_shift_interval = 0
excite_neuron_limit = 0.8

[[timelines]]
type = "Float"
min_value = 0
max_value = 5.0
capacity = 6
