[package]
name = "console_app"
version = "1.0.0"
edition = "2021"

[dependencies]
console_ui = { path = "../console_ui" }
rnn_core = { path = "../rnn_core" }
timeline_helpers = { path = "../timeline_helpers" }
tokio = { version = "1.40.0", features = ["full"] }
